builders:
  dart_mappable:
    import: "package:dart_mappable/builder.dart"
    builder_factories: [ "buildMappable" ]
    build_extensions: { "lib/$lib$": [ "lib/main.mapper.dart" ] }
    auto_apply: root_package
    build_to: source

targets:
  $default:
    builders:
      dart_mappable:
        generate_for:
          - test/test.dart
        options:
          caseStyle: snakeCase
          enumCaseStyle: camelCase
          libraries:
            test/models/:
              exclude: [ PlayerHooks, JeansHooks ]
